### ISSUE TITLE
Use web server to forward request.

### ISSUE THREAD

**Issue by likecreep** [linuxserver/docker-smokeping#114] opened 2021-06-13 13:09 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

As my 443 port is bind to a web server, so I want to forward requests from my web server to the docker smokeping.
## Current Behavior

Can not get it to work.
## Alternatives Considered

Use Caddy or Nginx as a web server. But I don't know how to config it to get it to work.

**Comment by tobbenb** [comment] 2021-06-13 13:30
That is a support question and is a question for either smokeping or the reverse proxy you are using. Closing this as it's not a bug.
You can try to ask in the other-support channel of our discord server. 
https://support.linuxserver.io

**Closed by tobbenb** 2021-06-13 13:30 UTC
